### ISSUE TITLE
package is focused on jupyter notebooks

### ISSUE THREAD

**Issue by cellofellow** [jbogaardt/GLMUtility#4]
I'd like to be able to install and use this package without any jupyter/ipython support. This for running the model on a server where these packages are unnecessary.

This would probably require these changes:

* [x] Split the GLM class into one without visualizations (Core? or something like that) and one with (equal in functionality with current class.)
  - This may require creating two modules, so that the core module doesn't import any of the bokeh etc dependencies.
  - Also, the core module shouldn't ever read/write files to disk. It should only read data passed in from memory. File access is a separate concern.
* [x] Define an `extras_require` section in the setup file, allowing to install with jupyter dependencies or not.

**Comment by jbogaardt** [comment]
Separations of concerns is a good idea.  I think the easiest thing to do is to strip out the UI methods and then throw them into a new class that inherits from the core `GLMUtility` class.  The UI methods are:
`view, lift_chart, head_to_head, create_comparisons, view_comparisons, clear_comparisons, get_comparisons, get_comparisons_count, give_comparisons, static_view, create_lift, view_lifts, clear_lifts, get_lifts, get_lifts_count, give_lifts`.  

In order to not break existing code, I think I'll have `GLMUtilityBase` as the core and will put that in a separate module and then will make `GLMUtility` with the UI dependencies.

**Comment by jbogaardt** [comment]
I've separated the package into two.  You should be able to access the core from /GLMUtility/Base/Base.py 
Not well-versed in `extra_require`, but at least the core does not have any references to bokeh or ipywidgets

**Comment by cellofellow** [comment]
Here's all you need to do to get the `extra_require` to work.

```
diff --git a/setup.py b/setup.py
index 75ef10a..c15828d 100644
--- a/setup.py
+++ b/setup.py
@@ -19,12 +19,16 @@ setuptools.setup(
         'Operating System :: OS Independent',
     ],
     install_requires=[
-        'bokeh',
-        'ipywidgets',
         'numpy',
         'pandas',
         'pyyaml',
         'scipy',
         'statsmodels',
     ],
+    extras_require={
+        'jupyter': [
+            'bokeh',
+            'ipywidgets',
+        ],
+    }
 )

```

**Comment by jbogaardt** [comment]
Marking as closed.  If I missed something, let me know.
